org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true

loader_version=0.18.4
loom_version=1.15-SNAPSHOT

mod_id=minecraft-xiv
mod_name=Minecraft XIV
mod_description=Changes Minecraft's third-person controls to be more like FFXIV.
mod_version=1.4.0-alpha.3
mod_group=wtf.kity
mod_author=ashkitten
mod_license=LGPL-3.0